plugins {
	alias libs.plugins.fabric.loom
	alias libs.plugins.shadow
	alias libs.plugins.publish
}

version = '2.1.0'
group = 'org.samo_lego'

base {
	archivesName = 'antilogout'
}

repositories {
	maven { url = 'https://maven.fabricmc.net/' }
	maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
	maven { url = 'https://jitpack.io' }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"modid" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

configurations {
    shadowOnly
}

dependencies {
	minecraft libs.minecraft
	mappings "${libs.yarn.get()}:v2"
	modImplementation libs.fabric.loader
	modImplementation libs.fabric.api

	modImplementation libs.fabric.permissions
	implementation libs.config.core
	implementation libs.config.toml
	shadowOnly libs.config.core
	shadowOnly libs.config.toml
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

tasks.withType(AbstractArchiveTask).configureEach {
	preserveFileTimestamps = false
	reproducibleFileOrder = true

	filePermissions {
		user.read = true
		user.write = true
		user.execute = false

		group.read = true
		group.write = false
		group.execute = false

		other.read = true
		other.write = false
		other.execute = false
	}

	dirPermissions {
		user.read = true
		user.write = true
		user.execute = true

		group.read = true
		group.write = false
		group.execute = true

		other.read = false
		other.write = false
		other.execute = true
	}
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

shadowJar {
    configurations = [project.configurations.shadowOnly]
    relocate 'com.electronwill.nightconfig', 'org.samo_lego.antilogout.shadow.nightconfig'
}
remapJar {
    dependsOn shadowJar
    input.set(shadowJar.archiveFile)
}

def ENV = System.getenv()

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = 'antilogout'
			from components.java
		}
	}
	repositories {
		// Add repositories to publish to here.
	}
}