[versions]
minecraft = "1.21.8"
fabric-loader = "0.19.3"
fabric-api = "0.136.1+1.21.8"
fabric-permissions = "0.4.1"

yarn = "1.21.8+build.1"

config-core = "3.9.0"
config-toml = "3.9.0"


fabric-loom = "1.13.6"

shadow = "8.1.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }

yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

config-core = { module = "com.electronwill.night-config:core", version.ref = "config-core" }
config-toml = { module = "com.electronwill.night-config:toml", version.ref = "config-toml" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }

shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
publish = { id = "maven-publish" }
