[versions]
minecraft = "1.21.8"
fabric-loader = "0.19.3"
fabric-api = "0.136.1+1.21.8"

yarn = "1.21.8+build.1"


fabric-loom = "1.13.6"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
